<a href="https://colab.research.google.com/github/rkmaccha/FlaskWebApp_ML_Basic/blob/main/DummyProject_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Bibliotecas necessárias

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

##### Lendo o arquivo com dados para predição

In [2]:
df = pd.read_csv("precos_casas.csv")

In [3]:
df.head()

area  bedrooms  age   price
0   230         3   20  620000
1    55         2   15  315000
2   110         4   16  680000
3    62         3   30  450000
4    44         1    8  198000

In [4]:
df.shape

(12, 4)

In [5]:
df

area  bedrooms  age   price
0    230         3   20  620000
1     55         2   15  315000
2    110         4   16  680000
3     62         3   30  450000
4     44         1    8  198000
5    160         3   10  590000
6     98         3    2  650000
7    266         4   12  760000
8     71         2   18  540000
9    130         4   30  670000
10    55         2    8  380000
11    90         3    8  410000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      12 non-null     int64
 1   bedrooms  12 non-null     int64
 2   age       12 non-null     int64
 3   price     12 non-null     int64
dtypes: int64(4)
memory usage: 512.0 bytes


##### Verificando se existe valores nulos

In [7]:
df.isnull()

area  bedrooms    age  price
0   False     False  False  False
1   False     False  False  False
2   False     False  False  False
3   False     False  False  False
4   False     False  False  False
5   False     False  False  False
6   False     False  False  False
7   False     False  False  False
8   False     False  False  False
9   False     False  False  False
10  False     False  False  False
11  False     False  False  False

In [8]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

##### Fazendo a média dos valores dos quartos

In [9]:
median_br = df['bedrooms'].median()

In [10]:
median_br

3.0

In [11]:
df['bedrooms'] = df['bedrooms'].fillna(median_br)

In [12]:
df

area  bedrooms  age   price
0    230         3   20  620000
1     55         2   15  315000
2    110         4   16  680000
3     62         3   30  450000
4     44         1    8  198000
5    160         3   10  590000
6     98         3    2  650000
7    266         4   12  760000
8     71         2   18  540000
9    130         4   30  670000
10    55         2    8  380000
11    90         3    8  410000

In [13]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

##### Dividindo os valores em variaveis x e y

In [14]:
X= df.drop(columns=['price'],axis=1)
y = df['price']

##### Criando o modelo de regressão linear

In [15]:
reg_model = LinearRegression()

In [16]:
reg_model.fit(X,y)

LinearRegression()

In [17]:
reg_model.predict([[70,3,18]])

c:\Users\elton.oliveira\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([506462.31061353])

##### Porcentagem de precisão da predição

In [18]:
reg_model.predict([[110,5,8]])

c:\Users\elton.oliveira\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([800748.84032999])

In [19]:
reg_model.score(X,y)

0.8150916800993213

##### Importando um arquivo Pickle (https://docs.python.org/pt-br/3/library/pickle.html)

In [20]:
import pickle

with open("lr_multimodel.pkl","wb") as f:
  pickle.dump(reg_model,f)

In [21]:
with open("lr_multimodel.pkl","rb") as f:
  model = pickle.load(f)

In [22]:
model.predict([[110,5,8]])

c:\Users\elton.oliveira\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([800748.84032999])